# Generated by Django 4.0.6 on 2022-07-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WORD',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='단어명')),
                ('meaning', models.CharField(max_length=500, verbose_name='단어뜻')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz', models.BooleanField(default=False)),
                ('quiz_meaning', models.CharField(blank=True, max_length=500, verbose_name='퀴즈뜻')),
            ],
            options={
                'db_table': 'WORD_board',
            },
        ),
        migrations.CreateModel(
            name='Wrong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word')),
            ],
            options={
                'db_table': 'WRONG_borad',
            },
        ),
    ]
