# Generated by Django 3.2.9 on 2021-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WORD',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='단어명')),
                ('meaning', models.CharField(max_length=200, verbose_name='단어뜻')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'WORD_board',
            },
        ),
    ]
