# Generated by Django 3.2.9 on 2021-12-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QUIZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='퀴즈')),
                ('one', models.CharField(max_length=30, verbose_name='보기1')),
                ('two', models.CharField(max_length=30, verbose_name='보기2')),
                ('three', models.CharField(max_length=30, verbose_name='보기3')),
                ('four', models.CharField(max_length=30, verbose_name='보기4')),
                ('five', models.CharField(max_length=30, verbose_name='보기5')),
                ('answer', models.CharField(max_length=30, verbose_name='정답')),
            ],
            options={
                'db_table': 'QUIZ_board',
            },
        ),
        migrations.CreateModel(
            name='WORD',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='단어명')),
                ('meaning', models.CharField(max_length=200, verbose_name='단어뜻')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'WORD_board',
            },
        ),
    ]
