# Generated by Django 4.0.4 on 2022-05-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=200, verbose_name='단어명'),
        ),
    ]
