# Generated by Django 4.0.4 on 2022-05-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.CharField(max_length=500, verbose_name='단어뜻'),
        ),
    ]
