# Generated by Django 4.0.4 on 2022-05-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_word_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='quiz',
            field=models.BooleanField(default=False),
        ),
    ]
