# Generated by Django 4.0.4 on 2022-05-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_word_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QUIZ',
        ),
    ]
