# Generated by Django 4.0.6 on 2022-07-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='question',
            field=models.CharField(default='nan', max_length=500, verbose_name='퀴즈뚯'),
            preserve_default=False,
        ),
    ]
