# Generated by Django 4.0.6 on 2022-07-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_word_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='question',
        ),
    ]
