# Generated by Django 4.0.6 on 2022-07-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_remove_word_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='quiz_meaning',
            field=models.CharField(blank=True, max_length=500, verbose_name='퀴즈뜻'),
        ),
    ]
